### ISSUE TITLE
verifying requests come from alexa?

### ISSUE THREAD

**Issue by TerribleDev** [DanElbert/alexa_skills_ruby#2]
I saw in the docs for hosting custom skills, requests need to be verified if they come from alexa. Does this library do that? I can't seem to find any code that alludes to any mechanisms, but I could be missing something.

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/developing-an-alexa-skill-as-a-web-service

**Comment by DanElbert** [comment]
You're right, this library did not validate the signature or timestamp.

I've added the verification checks and bumped the version to 1.0.0 (since the API has changed slightly)
